version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - 'dependencies'
      - 'github-actions'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: auto
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "npm"
    directory: "/contract"
    schedule:
      interval: "daily"
    labels:
      - 'dependencies'
      - 'npm'
      - 'contract'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "npm"
    directory: "/counter-cli"
    schedule:
      interval: "daily"
    labels:
      - 'dependencies'
      - 'npm'
      - 'counter-cli'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
